import '../styles/globals.css'
import type {AppProps} from 'next/app'
import {MoralisProvider} from 'react-moralis'
import {NotificationProvider} from 'web3uikit'
import Head from 'next/head'

const SERVER_URL = process.env.NEXT_PUBLIC_MORALIS_SERVER_URL || ''
const APP_ID = process.env.NEXT_PUBLIC_MORALIS_APP_ID || ''

function MyApp({Component, pageProps}: AppProps) {

  return (
    <>
      <Head>
        <title>NFT marketplace</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <MoralisProvider serverUrl={SERVER_URL} appId={APP_ID}>
        <NotificationProvider>
          <Component {...pageProps} />
        </NotificationProvider>
      </MoralisProvider>
    </>
  )
}

export default MyApp
